version: "3.9"

services:
    nginx:
        image: nginx:1.25-alpine
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./application/public:/var/www/application/public

    php-fpm:
        build:
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - ./application:/var/www/application
            - ./application:/var/www/application

    database:
        image: postgres:16.2-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - database:/var/lib/postgresql/data

volumes:
    database: ~